#!/bin/bash -eu
cd "$(readlink -fn "$(dirname "$0")")"
PHP=(
    "${PHP:-php}"
    -dapc.enabled=on
    -dapc.enable_cli=on
    -dzend.assertions=1
    -dpcov.enabled=1
    -dpcov.directory="$PWD"
    -dpcov.exclude='@/(Tests|vendor)/@'
    -dzend_extension=xdebug.so -dxdebug.mode=debug
)
rm -rf Tests/Import/import_builder_test
"${PHP[@]}" vendor/bin/phpunit "$@"
