<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DropProfile extends \Doctrine1\Migration\Base
{
    public function migrate($direction)
    {
        $direction = $direction == 'up' ? 'down':'up';
        $this->table($direction, 'migration_profile', ['id' => ['type' => 'integer', 'length' => 20, 'autoincrement' => true, 'primary' => true], 'name' => ['type' => 'string', 'length' => 255]], ['indexes' => [], 'primary' => [0 => 'id']]);
    }
}
